import type { Item } from "./types";

export const MOCK_ITEMS: Item[] = [
  {
    item_id: "mock-1",
    title: "พัดลมตั้งโต๊ะ 16 นิ้ว",
    description: "ใช้งาน 1 เทอม ย้ายหอเลยขาย นัดรับหอในได้",
    price: 350,
    status: "available",
    created_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    member_id: "m1",
    member: {
      member_id: "m1",
      name: "รุ่นพี่หอใน",
      email: "senior@up.ac.th",
      avatar_url: null,
      role: "member",
      is_banned: false,
      created_at: new Date().toISOString(),
    },
    images: [],
  },
  {
    item_id: "mock-2",
    title: "ตู้เย็น mini 3.5 คิว",
    description: "เย็นปกติ ประกันเหลือ นัดรับหน้ามอ",
    price: 2500,
    status: "available",
    created_at: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    member_id: "m1",
    member: {
      member_id: "m1",
      name: "รุ่นพี่หอใน",
      email: "senior@up.ac.th",
      avatar_url: null,
      role: "member",
      is_banned: false,
      created_at: new Date().toISOString(),
    },
    images: [],
  },
  {
    item_id: "mock-3",
    title: "หนังสือ Calculus แจกฟรี",
    description: "ขีดเขียนนิดหน่อย มารับเองที่คณะ ICT",
    price: 0,
    status: "available",
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    member_id: "m2",
    member: {
      member_id: "m2",
      name: "น้องปี 1",
      email: "freshy@up.ac.th",
      avatar_url: null,
      role: "member",
      is_banned: false,
      created_at: new Date().toISOString(),
    },
    images: [],
  },
];
